---
title: "Data Import"
output: github_document
---
```{r echo = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```


## Data Import: CSVs

Let's import data using the 'readr' package 

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_name(litters_df)
```


Look at the data

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

```{r, eval=FALSE}
view(litters_df)
```

```{r}
skimr::skim(litters_df)
```

'read_csv'options..

```{r}
read_csv("data/FAS_litters.csv", na = c("",999,88,"NA"))
```

## Other file formats 

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r}
lotr_words_df = 
  read_excel(
    "data/LotR_Words.xlsx",
    range = "B3:D6"
  )
```

## Still more formats ... 

Read in a SAS dataset.

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


## Data export

```{r}
write_csv(lotr_words_df, file = "data/lotr_words_df.csv")
```


## Why not base r?

```{r}
dont_do_this_df = read.csv("data/FAS_litters.csv")
##可以用下划线 不要用.
```

